import { TDataMahasiswaTataUsaha } from "./type";

export const dataMahasiswaTataUsaha: TDataMahasiswaTataUsaha[] = [
  {
    nim: "41037006222222",
    nama: "Aldo Febrian Dirgantara Mulyana",
    angkatan: "2020",
    program: "Reguler",
    kelasSemester: "A1/7",
    dosenPa: "Ani Amaliah",
    status: "Aktif",
  },
  {
    nim: "41037006222222",
    nama: "M Nurfahmi Sugiarto",
    angkatan: "2020",
    program: "Karyawan",
    kelasSemester: "A1/7",
    dosenPa: "Tedjo Darmanto",
    status: "Tidak Aktif",
  },
  {
    nim: "41037006222222",
    nama: "Randika",
    angkatan: "2020",
    program: "KIP - K",
    kelasSemester: "A1/7",
    dosenPa: "Siti Nur",
    status: "Aktif",
  },
  {
    nim: "41037006222222",
    nama: "Rizal Syaepulloh",
    angkatan: "2020",
    program: "Beasiswa PMDK",
    kelasSemester: "A1/7",
    dosenPa: "Yenni Fatman",
    status: "Tidak Aktif",
  },
  {
    nim: "41037006222222",
    nama: "M Rian Ardiansyah",
    angkatan: "2021",
    program: "Beasiswa NU",
    kelasSemester: "A1/5",
    dosenPa: "Ricky Yoseptri",
    status: "Aktif",
  },
  {
    nim: "41037006222222",
    nama: "Ayu Sri Rahayu",
    angkatan: "2020",
    program: "Beasiswa NP",
    kelasSemester: "A2/7",
    dosenPa: "Galih",
    status: "Cuti",
  },
  {
    nim: "41037006222222",
    nama: "Astie Noer Hadiyanti",
    angkatan: "2020",
    program: "Beasiswa NPD",
    kelasSemester: "A1/7",
    dosenPa: "Tedjo Darmanto",
    status: "MBKM",
  },
  {
    nim: "41037006222222",
    nama: "Ajid Zakaria Yahya",
    angkatan: "2019",
    program: "Beasiswa MN",
    kelasSemester: "A1/7",
    dosenPa: "Tedjo Darmanto",
    status: "Aktif",
  },
];
