import { atom } from "recoil";

export const answerState = atom({
  key: "answer-state",
  default: {
    answer: 0,
  },
});

export const questionState = atom({
  key: "question-state",
  default: 0,
});
export const queyQuestionState = atom({
  key: "queyQuestionState",
  default: [
    {
      no: 1,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "In golf, what name is given to a hole score of two under par?",
      correct_answer: "Eagle",
      incorrect_answers: ["Birdie", "Bogey", "Albatross"],
    },
    {
      no: 2,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which English football club has the nickname 'The Foxes'?",
      correct_answer: "Leicester City",
      incorrect_answers: ["Northampton Town", "Bradford City", "West Bromwich Albion"],
    },
    {
      no: 3,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which team won the 2014 FIFA World Cup in Brazil?",
      correct_answer: "Germany",
      incorrect_answers: ["Argentina", "Brazil", "Netherlands"],
    },

    {
      no: 4,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question:
        "Which year did Jenson Button win his first ever Formula One World Drivers' Championship?",
      correct_answer: "2009",
      incorrect_answers: ["2010", "2007", "2006"],
    },
    {
      no: 5,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Who won the 2017 Formula One World Drivers' Championship?",
      correct_answer: "Lewis Hamilton",
      incorrect_answers: ["Sebastian Vettel", "Nico Rosberg", "Max Verstappen"],
    },
    {
      no: 6,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 7,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 8,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 9,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 10,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 11,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 12,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 13,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 14,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 15,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 16,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "In golf, what name is given to a hole score of two under par?",
      correct_answer: "Eagle",
      incorrect_answers: ["Birdie", "Bogey", "Albatross"],
    },

    {
      no: 17,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which English football club has the nickname 'The Foxes'?",
      correct_answer: "Leicester City",
      incorrect_answers: ["Northampton Town", "Bradford City", "West Bromwich Albion"],
    },
    {
      no: 18,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which team won the 2014 FIFA World Cup in Brazil?",
      correct_answer: "Germany",
      incorrect_answers: ["Argentina", "Brazil", "Netherlands"],
    },

    {
      no: 19,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question:
        "Which year did Jenson Button win his first ever Formula One World Drivers' Championship?",
      correct_answer: "2009",
      incorrect_answers: ["2010", "2007", "2006"],
    },
    {
      no: 20,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Who won the 2017 Formula One World Drivers' Championship?",
      correct_answer: "Lewis Hamilton",
      incorrect_answers: ["Sebastian Vettel", "Nico Rosberg", "Max Verstappen"],
    },
    {
      no: 21,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 22,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 23,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 24,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 25,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 26,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 27,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 28,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 29,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
    {
      no: 30,
      category: "Sports",
      type: "multiple",
      difficulty: "easy",
      question: "Which two teams played in Super Bowl XLII?",
      correct_answer: "The New York Giants & The New England Patriots",
      incorrect_answers: [
        "The Green Bay Packers & The Pittsburgh Steelers",
        "The Philadelphia Eagles & The New England Patriots",
        "The Seattle Seahawks & The Denver Broncos",
      ],
    },
  ],
});

export const timerState = atom({
  key: "timer-state",
  default: 59,
});

export const incorrectAnswers = atom({
  key: "incorrect-answers",
  default: 0,
});
