import { TDataPegawai } from "./types";

export const dataPegawai: TDataPegawai[] = [
  {
    name: "Fenny Oktaviani",
    nip: "123456789",
    faculty: "Fakultas Teknik",
    major: "Teknik Informatika",
    jafung: "Guru Besar",
    job_unit: "Guru Besar",
    sk: "Document",
    lecturer_certificate: "Document",
    profession_certificate: "Document",
    status: "Aktif",
  },
  {
    name: "Maulana Sodiqin",
    nip: "123456789",
    faculty: "Fakultas Teknik",
    major: "Teknik Informatika",
    jafung: "Guru Besar",
    job_unit: "Guru Besar",
    sk: "Document",
    lecturer_certificate: "Document",
    profession_certificate: "Document",
    status: "Tidak Aktif",
  },
  {
    name: "Rian Ardiansyah",
    nip: "123456789",
    faculty: "Fakultas Teknik",
    major: "Teknik Informatika",
    jafung: "Guru Besar",
    job_unit: "Guru Besar",
    sk: "Document",
    lecturer_certificate: "Document",
    profession_certificate: "Document",
    status: "Aktif",
  },
];
