import { Montserrat } from "next/font/google";
import "./global.css";

export const metadata = {
  title: "Welcome to web/tata-usaha",
  description: "Generated by create-nx-workspace",
};

const monserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${monserrat.className}`}>{children}</body>
    </html>
  );
}
