import { TDataMataKuliah } from "./type";

export const cardData = [
  {
    heading1: "IPS | IPK",
    heading2: "3.7 | 3.5",
    class: "bg-green-200",
  },
  {
    heading1: "kelas",
    heading2: "reguler",
    class: "bg-green-200",
  },
  {
    heading1: "SKS Maksimum",
    heading2: "144 SKS",
    class: "bg-yellow-500",
  },
  {
    heading1: "Dosen PA/Wali",
    heading2: "Ani Amaliyah, ST, M.Kom.",
    class: "bg-error-600",
  },
];

export const dataMataKuliah: TDataMataKuliah[] = [
  {
    kode_mk: "FT001",
    nama_mk: "Data Visualisasi",
    sks: "2",
    kelas: "Reguler A.1",
    jadwal: "Senin, 10:00-12:00",
    ruangan: "Lab Komputer Lt. 3",
    dosen: "Isbandi ST.MT",
    status: "Disetujui",
  },
  {
    kode_mk: "FT002",
    nama_mk: "Machine Learning",
    sks: "2",
    kelas: "Reguler A.2",
    jadwal: "Senin, 10:00-12:00",
    ruangan: "Kelas C.201 Lt.2",
    dosen: "Isbandi ST.MT",
    status: "Belum Disetujui",
  },
  {
    kode_mk: "FT003",
    nama_mk: "Data Visualisasi",
    sks: "2",
    kelas: "Karyawan",
    jadwal: "Senin, 17:00-19:00",
    ruangan: "Lab Komputer Lt. 3",
    dosen: "Isbandi ST.MT",
    status: "Disetujui",
  },
  {
    kode_mk: "FT004",
    nama_mk: "Machine Learning",
    sks: "2",
    kelas: "Reguler A.1",
    jadwal: "Senin, 08:00-10:00",
    ruangan: "Kelas C.201 Lt.2",
    dosen: "Isbandi ST.MT",
    status: "Belum Disetujui",
  },
  {
    kode_mk: "FT005",
    nama_mk: "Data Visualisasi ",
    sks: "2",
    kelas: "Reguler A.2",
    jadwal: "Senin, 10:00-12:00 ",
    ruangan: "Lab Komputer Lt. 3",
    dosen: "Isbandi ST.MT",
    status: "Disetujui",
  },
  {
    kode_mk: "FT006",
    nama_mk: "Data Visualisasi",
    sks: "2",
    kelas: "Reguler A.1",
    jadwal: "Senin, 10:00-12:00",
    ruangan: "Lab Komputer Lt. 3",
    dosen: "Isbandi ST.MT",
    status: "Disetujui",
  },
  {
    kode_mk: "FT007",
    nama_mk: "Machine Learning",
    sks: "2",
    kelas: "Reguler A.2",
    jadwal: "Senin, 10:00-12:00",
    ruangan: "Kelas C.201 Lt.2",
    dosen: "Isbandi ST.MT",
    status: "Belum Disetujui",
  },
  {
    kode_mk: "FT008",
    nama_mk: "Data Visualisasi",
    sks: "2",
    kelas: "Karyawan",
    jadwal: "Senin, 17:00-19:00",
    ruangan: "Lab Komputer Lt. 3",
    dosen: "Isbandi ST.MT",
    status: "Disetujui",
  },
  {
    kode_mk: "FT009",
    nama_mk: "Machine Learning",
    sks: "2",
    kelas: "Reguler A.1",
    jadwal: "Senin, 08:00-10:00",
    ruangan: "Kelas C.201 Lt.2",
    dosen: "Isbandi ST.MT",
    status: "Disetujui",
  },
  {
    kode_mk: "FT010",
    nama_mk: "Data Visualisasi",
    sks: "2",
    kelas: "Reguler A.2",
    jadwal: "Senin, 10:00-12:00 ",
    ruangan: "Lab Komputer Lt. 3",
    dosen: "Isbandi ST.MT",
    status: "Belum Disetujui",
  },
];
