import { Montserrat } from 'next/font/google';
import './global.css';

export const metadata = {
  title: 'Welcome to siakad',
  description: 'Generated by create-nx-workspace',
};

const monserrat = Montserrat({
  subsets: ['latin'],
  weight: '400',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={`${monserrat.className}`}>
      <body>{children}</body>
    </html>
  );
}
