import { Montserrat } from "next/font/google";
import "./global.css";
import { AuthProvider, QueryProvider, RecoilProvider } from "@uninus/web/providers";

export const metadata = {
  title: "Welcome to web/siakad",
  description: "Generated by create-nx-workspace",
};

const monserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout(props: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${monserrat.className}`}>
        <AuthProvider>
          <QueryProvider>
            <RecoilProvider>
              <main key="landing-siakad">{props.children}</main>
              <div key="modal-landing" id="modal-landing" />
            </RecoilProvider>
          </QueryProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
