export enum EJob {
  TNI = 'TNI',
  POLRI = 'POLRI',
  PNS = 'PNS',
  BURUH = 'BURUH',
  SWASTA = 'SWASTA',
  WIRAUSAHA = 'WIRAUSAHA',
  WIRASWASTA = 'WIRASWASTA',
  PETANI = 'PETANI',
  GURU = 'GURU',
  DOKTER = 'DOKTER',
  PERAWAT = 'PERAWAT',
  PETERNAK = 'PETERNAK',
  NELAYAN = 'NELAYAN',
}

export enum ETniPosition {
  JENDERAL_TNI = 'Jenderal TNI',
  LETJEN_TNI = 'Letnan Jenderal (Letjen) TNI',
  MAYJEN_TNI = 'Mayor Jenderal (Mayjen) TNI',
  BRIGJEN_TNI = 'Brigadir Jenderal (Brigjen) TNI',
  KOLOL_TNI = 'Kolonel',
  LETKOL_TNI = 'Letnan Kolonel (Letkol)',
  MAJOR_TNI = 'Mayor',
  KAPTEN_TNI = 'Kapten',
  LETTU_TNI = 'Letnan Satu (Lettu)',
  LETDA_TNI = 'Letnan Dua (Letda)',
  PELTU_TNI = 'Pembantu Letnan Satu (Peltu)',
  PELDA_TNI = 'Pembantu Letnan Dua (Pelda)',
  SERMA_TNI = 'Sersan Mayor (Serma)',
  SERKA_TNI = 'Sersan Kepala (Serka)',
  SERTU_TNI = 'Sersan Satu (Sertu)',
  SERDA_TNI = 'Sersan Dua (Serda)',
  KOPKA_TNI = 'Kopral Kepala (Kopka)',
  KOPTU_TNI = 'Kopral Satu (Koptu)',
  KOPDA_TNI = 'Kopral Dua (Kopda)',
  PRAKA_TNI = 'Prajurit Kepala (Praka)',
  PRATU_TNI = 'Prajurit Satu (Pratu)',
  PRADA_TNI = 'Prajurit Dua (Prada)',
}

export enum EPolriPosition {
  JENDERAL_POLISI = 'Jenderal Polisi',
  KOMJEN_POLISI = 'Komisaris Jenderal Polisi (Komjen Pol)',
  IRJEN_POLISI = 'Inspektur Jenderal Polisi (Irjen Pol)',
  KOMBES_POLISI = 'Komisaris Besar Polisi (Kombes Pol)',
  AKBP_POLISI = 'Ajun Komisaris Besar Polisi (AKBP)',
  KOMPOL_POLISI = 'Komisaris Polisi (Kompol)',
  PAMA_POLISI = 'Perwira Pertama (Pama)',
  AKP_POLISI = 'Ajun Komisaris Polisi (AKP)',
  IPTU_POLISI = 'Inspektur Polisi Satu (Iptu)',
  IPDA_POLISI = 'Inspektur Polisi Dua (Ipda)',
  AIPTU_POLISI = 'Ajun Inspektur Polisi Satu (Aiptu)',
  AIPDA_POLISI = 'Ajun Inspektur Polisi Dua (Aipda)',
  BRIPKA_POLISI = 'Brigadir Polisi Kepala (Bripka)',
  BRIGPOL_POLISI = 'Brigadir Polisi (Brigpol)',
  BRIPTU_POLISI = 'Brigadir Polisi Satu (Briptu)',
  BRIPDA_POLISI = 'Brigadir Polisi Dua (Bripda)',
  ABRIP_POLISI = 'Ajun Brigadir Polisi (Abrip)',
  ABRIP2_POLISI = 'Ajun Brigadir Polisi (Abriptu)',
  ABRIP3_POLISI = 'Ajun Brigadir Polisi (Abripda)',
  BHARAKA_POLISI = 'Bhayangkara Kepala (Bharaka)',
  BHARATU_POLISI = 'Bhayangkara Satu (Bharatu)',
  BHARADA_POLISI = 'Bhayangkara Dua (Bharada)',
}

export enum EPnsPosition {
  GOLONGAN_IA = 'Golongan Ia',
  GOLONGAN_IB = 'Golongan Ib',
  GOLONGAN_IC = 'Golongan Ic',
  GOLONGAN_ID = 'Golongan Id',
  GOLONGAN_IIA = 'Golongan IIa',
  GOLONGAN_IIB = 'Golongan IIb',
  GOLONGAN_IIC = 'Golongan IIc',
  GOLONGAN_IID = 'Golongan IId',
  GOLONGAN_IIIA = 'Golongan IIIa',
  GOLONGAN_IIIB = 'Golongan IIIb',
  GOLONGAN_IIIC = 'Golongan IIIc',
  GOLONGAN_IIID = 'Golongan IIId',
}
