import "./global.css";
import { Montserrat } from "next/font/google";
export const metadata = {
  title: "Welcome to web/tracer-alumni",
  description: "Generated by create-nx-workspace",
};
const monserrat = Montserrat({
  subsets: ["latin"],
  weight: "400",
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className={`${monserrat.className}`}>
        <main>{children}</main>
      </body>
    </html>
  );
}
