import { TDataBiayaKuliah } from "./type";

export const dataBiayaKuliah: TDataBiayaKuliah[] = [
  {
    kode_bayar: "FT001",
    bayar: "Biaya Formulir",
    biaya: "Rp. 250.000",
    potongan: "Rp. 0",
    total_bayar: "Rp. 250.000",
    status: "Lunas",
  },
  {
    kode_bayar: "FT002",
    bayar: "Uang Kuliah Tetap(UKT) Semester 1",
    biaya: "Rp. 600.000",
    potongan: "Rp. 0",
    total_bayar: "Rp. 600.000",
    status: "Belum Membayar",
  },
  {
    kode_bayar: "FT003",
    bayar: "Biaya Formulir",
    biaya: "Rp. 400.000",
    potongan: "Rp. 0",
    total_bayar: "Rp. 400.000",
    status: "Lunas",
  },
  {
    kode_bayar: "FT004",
    bayar: "Uang Kuliah Tetap(UKT) Semester 1",
    biaya: "Rp. 250.000",
    potongan: "Rp. 0",
    total_bayar: "Rp. 250.000",
    status: "Belum Membayar",
  },
  {
    kode_bayar: "FT005",
    bayar: "Biaya Formulir ",
    biaya: "Rp. 600.000",
    potongan: "Rp. 0 ",
    total_bayar: "Rp. 600.000",
    status: "Lunas",
  },
  {
    kode_bayar: "FT006",
    bayar: "Biaya Formulir",
    biaya: "Rp. 250.000",
    potongan: "Rp. 0",
    total_bayar: "Rp. 250.000",
    status: "Lunas",
  },
  {
    kode_bayar: "FT007",
    bayar: "Uang Kuliah Tetap(UKT) Semester 1",
    biaya: "Rp. 600.000",
    potongan: "Rp. 0",
    total_bayar: "Rp. 250.000",
    status: "Belum Membayar",
  },
  {
    kode_bayar: "FT008",
    bayar: "Biaya Formulir",
    biaya: "Rp. 400.000",
    potongan: "Rp. 0",
    total_bayar: "Rp. 400.000",
    status: "Lunas",
  },
  {
    kode_bayar: "FT009",
    bayar: "Uang Kuliah Tetap(UKT) Semester 1",
    biaya: "Rp. 250.000",
    potongan: "Rp. 0",
    total_bayar: "Rp. 250.000",
    status: "Lunas",
  },
  {
    kode_bayar: "FT010",
    bayar: "Biaya Formulir",
    biaya: "Rp. 600.000",
    potongan: "Rp. 0 ",
    total_bayar: "Rp. 600.000",
    status: "Belum Membayar",
  },
];
