export const studentData = {
  father_name: undefined,
  father_status_id: 0,
  father_education_id: 0,
  father_occupation_id: 0,
  father_salary_id: 0,
  mother_name: undefined,
  mother_status_id: 0,
  mother_education_id: 0,
  mother_occupation_id: 0,
  mother_salary_id: 0,
  parent_address: undefined,
  parent_province_id: 0,
  parent_city_id: 0,
  parent_subdistrict_id: 0,
  guardian_name: undefined,
  guardian_status_id: 0,
  guardian_education_id: 0,
  guardian_occupation_id: 0,
  guardian_salary_id: 0,
  guardian_address: null,
  guardian_province_id: 0,
  guardian_city_id: 0,
  guardian_subdistrict_id: 0,
};
