#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

yarn run nx run-many --target=lint --projects=web-akreditasi,web-evaluasi,web-keuangan,web-neo-feeder,web-pegawai,web-pmb-user,web-pmb-admin,web-siakad,web-smart-dashboard,web-tata-usaha,web-tracer-alumni,web-lms,api,api-auth,api-location,api-pmb,web-components,api-controllers,entities,api-master,api-models,api-modules,web-modules,api-models,web-providers,api-services,web-services,utilities,api-strategies,api-guard,web-layouts

yarn run nx run-many --target=build --projects=web-akreditasi,web-evaluasi,web-keuangan,web-neo-feeder,web-pegawai,web-pmb-user,web-pmb-admin,web-siakad,web-smart-dashboard,web-tata-usaha,web-tracer-alumni,web-lms,api,api-auth,api-location,api-pmb,web-components,api-controllers,entities,api-master,api-models,api-modules,web-modules,api-models,web-providers,api-services,web-services,utilities,api-strategies,api-guard,web-layouts


